### ISSUE TITLE
Unexpected string in settings.json

### ISSUE THREAD

**Issue by Flauschie** [JohnMcLear/ep_button_link#1]
I tried adding the lines you specified before everything in setting.json, after everything, after the first "{"-bracket and I am always receiving the following error.

What am I doing wrong?

```
[2015-03-14 12:56:23.298] [ERROR] console - There was an error processing your settings.json file: Unexpected string
RESTART!
```

**Comment by JohnMcLear** [comment]
It's JSON, you will need to either prefix ``"ep_button_link"``: with a ``,`` or suffix all of the settings with a ``,``

Please read about JSON and/or run it through a validator before posting anothe rissue.

Thanks.

**Comment by Flauschie** [comment]
my bad in the morning, sorry for this! really sorry
