### ISSUE TITLE
Not working properly with the plugin aa_file_menu_toolbar.

### ISSUE THREAD

**Issue by Sergio3** [JohnMcLear/ep_button_link#2]
Hello John,

I realized you plugin style (css) is not working properly with aa_file_menu_toolbar. The upper bar looks stripped when I added the ep_button_link rules ("text", "link", "classes", "before" and "after") in settings.json. If I don't add the "ep_button_link" : { } at settings.json, the example button "NO TEXT SET" appears correctly.

Maybe I'm doing something wrong?

Thank you very much in advance for your plugin and support.

**Comment by JohnMcLear** [comment]
Can you please provide steps to replicate?

**Comment by Sergio3** [comment]
Thanks for your quick response. I've just installed the last version of etherpad-lite (1.5.6) and then the aa_file_menu_toolbar plugin from plugin manager. When I decided to install your ep_button_link from the plugin manager everything seemed to work properly and the button "NO TEXT SET" appears where it should, but if put the next configuration to settings.json:

  /*** ep_button_link ***/

  "ep_button_link": {

      "text": "WORKING",
      "link": "http://myworkinglink.com",
      "classes": "grouped-right",
      "before": "#timesliderlink",
      "after": "#timesliderlink"
    },

Then the button appears at the top-left of the bar menu between "File" and "Edit" dropdown menus, breaking the menu style.

Thanks a lot.

**Comment by JohnMcLear** [comment]
Fixed, please update and look at updated selectors in README :)

Thanks for the bug report.

**Comment by Sergio3** [comment]
Thank you again John :) I'll test it later, now I'm trying to solve another issue related directly to etherpad-lite plugin manager.

**Comment by Sergio3** [comment]
Everything is working fine now, thank you very much!!!!!
